modLoader="javafml"
loaderVersion="[42,)"
license="MIT"
issueTrackerURL="https://github.com/Low-Drag-MC/Shimmer/issues"

[[mods]]
modId="shimmer"
version="${file.jarVersion}"
displayName="Shimmer"
displayURL="https://github.com/Low-Drag-MC/Shimmer"
logoFile="icon.png"
credits="zomb_676, hypherionsa"
authors="KilaBash"
description='''Shimemr, make rendering vivid'''

[[dependencies.shimmer]]
    modId="forge"
    mandatory=true
    versionRange="[42,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.shimmer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
